# Linting rules for Sass/SCSS stylesheets
#   based on Hugo Giraudel's Sass guidelines,
#   https://sass-guidelin.es

extends: stylelint-config-sass-guidelines

options:
  formatter: stylish

files:
  include: '**/*.s+(a|c)ss'

rules:
  max-nesting-depth: 4
  selector-max-compound-selectors: 5
  selector-max-id: 2
