extends:
  - stylelint-config-sass-guidelines

rules:
  block-no-empty:
    - null
  declaration-property-value-blacklist:
    - null
  indentation:
    - tab
  max-nesting-depth:
    - 4
  number-leading-zero:
    - null
  number-no-trailing-zeros:
    - null
  property-no-vendor-prefix:
    - null
  selector-class-pattern:
    - null
  selector-max-compound-selectors:
    - 5
  selector-max-id:
    - 2
  selector-no-qualifying-type:
    - null
  value-no-vendor-prefix:
    - null
